service: serverless-portfolios
useDotenv: true

frameworkVersion: '2'

plugins:
  - serverless-offline
   
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  getPortfolio:
    handler: handler.getPortfolio
    events:
      - http:
          path: portfolios
          method: get
          cors: true
